### PR TITLE
Create hello.txt

### PR DESCRIPTION
**Pull request by Archess14**
check code line 32

### CODE REVIEW

**Comment by Volkhives** [comment]
Hello

**Review by Archess14 — COMMENTED** [review]
kulang ng ikaw

**Comment by Volkhives** [comment]
**Jerico <3 Daniela**

**Comment by rbjlnne** [comment]
ayie layag

**Comment by Volkhives** [comment]
**JERICO MADRIAGA <3 DANIELA OLIQUINO**

**Pull request closed without merging**
